import React, {useState} from 'react'

import Head from 'next/head'

import {
  Page, 
  Container,
  Row,
  Button,
  Input,
  Spacer,
  Text,
  Link,
  Image, 
  Display, 
  Grid,
  Tag, 
  Select,
  Card,
  Divider,
  Toggle,
  useTheme 
} from '@geist-ui/react'

// import * as Icon from '@geist-ui/react-icons'
import { Github, ChevronUpDown } from '@geist-ui/react-icons'

import Footer from "../components/footer"

import styles from '../styles/Home.module.css'

const MyComponent = () => <Button>Click Me</Button>

const Home = ({ onThemeChange, stars }) =>  {
  const theme = useTheme()
  
  const changeHandler = val => {
    onThemeChange && onThemeChange(val)
  }

  const switchThemes = () => {
    onThemeChange && onThemeChange(last => (last === 'dark' ? 'light' : 'dark'))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>PNG-API</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page dotBackdrop width="800px" padding={0}>
        <Page.Header>
          <Text h1>Welcome to <a href="https://pngx-api.cleverapps.io/stocks">PNGX-API Client!</a></Text>
        </Page.Header>

        <Card hoverable>
          <p>hoverable card.</p>
        </Card>

        <Divider />

        Next stars: {stars}

        <Text>
          The server uses them as hints and an internal algorithm chooses the best content to serve to the client.
          The algorithm is server-specific and not defined in the standard.
        </Text>

        <Display
          title="Geist UI"
          caption={
            <>
              Welcome to{' '}
              <Text span b>
                Geist UI
              </Text>{' '}
              and start learning more !
            </>
          }>
          <Image src="/vercel.svg" alt="logo" draggable={false} />
        </Display>

        <Link href='/graph'>Graph</Link>
        <MyComponent/>

        <Spacer />
        <Github />
        <Spacer w={1} inline />
        <Toggle onChange={switchThemes} />
        <Spacer h={.5} />

      <Select size="small" value={theme.type} onChange={changeHandler}>
        <Select.Option label>System preset</Select.Option>
        <Select.Option value="light">Light</Select.Option>
        <Select.Option value="dark">Dark</Select.Option>
        <Select.Option label>My custom</Select.Option>
        <Select.Option value="green">Green</Select.Option>
        <Select.Option value="red">Red</Select.Option>
      </Select>

      <Text type={'success'}>
        Success. <Tag>{theme.palette.success}</Tag>
      </Text>
      <Text type={'warning'}>
        Warning. <Tag>{theme.palette.warning}</Tag>
      </Text>
      <Text type={'error'}>
        Error. <Tag>{theme.palette.error}</Tag>
      </Text>
      <Text type={'secondary'}>
        Secondary (Uncovered). <Tag>{theme.palette.secondary}</Tag>
      </Text>

      <Footer/>

      </Page>

    </div>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('https://api.github.com/repos/chrisaugu/pngx-api');
  const json = await res.json();
  return { stars: json.stargazers_count };
}

export default Home
